version: "3.4"
services:
  identifier:
    image: semtech/mu-identifier:1.8.0
    links:
      - dispatcher:dispatcher
  dispatcher:
    image: semtech/mu-dispatcher:1.1.2
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
  db:
    image: semtech/mu-authorization:0.5.0
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
    volumes:
      - ./config/authorization:/config
    links:
      - virtuoso:virtuoso
  virtuoso:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
  resource:
    image: semtech/mu-cl-resources:1.18.0
    links:
      - db:database
    volumes:
      - ./config/resources:/config
  migrations:
    image: semtech/mu-migrations-service:0.5.1
    links:
      - virtuoso:database
    volumes:
      - ./config/migrations:/data/migrations
    environment:
      MU_SPARQL_TIMEOUT: "600"
