PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

DELETE { GRAPH ?g {
  ?folder a ext:Folder
}}
INSERT { GRAPH ?g  { 
  ?folder a nfo:Folder
}}
WHERE { GRAPH ?g {
  ?folder a ext:Folder
}}