PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX notable: <http://data.notable.redpencil.io/>

INSERT { GRAPH ?g {
  ?document nfo:belongsToContainer ?inbox .
}}

WHERE { GRAPH ?g {
  ?inbox a nfo:Folder ;
         skos:label "inbox" .

  ?document a notable:EditorDocument .
  FILTER NOT EXISTS {
    ?document nfo:belongsToContainer nfo:Folder .
  }
}}